### ISSUE TITLE
[2021][lace_gel]  Game Engine Library

### ISSUE THREAD

**Issue by charlie5** [AdaCore/Ada-SPARK-Crate-Of-The-Year#11]
# lace_gel

## Purpose

`Provides a 2D/3D game engine library.`
`Ada is the perfect vehicle for game development. Simple tasking to take advantage of multi-core CPU's, sensible OO via interface and tagged types, pragmatic exception handling and an ever growing rich collection of standardized runtime packages, all recommend Ada as the language of choice for modern day game development.`   

## Usage

`Useful for 2D/3D simulations, games and visualizations.`

## Design

`Uses 'box2d' and 'bullet' as back-ends for the rigid body physics.`
`openGL shaders are used for rendering.`
`openGL engine runs within its own task for performance.`
`Online games are supported via DSA/Polyorb.`
`Physics/graphics/animation support is via a Collada parser.`
`A custom set of generic packages provides math support.`
`An extensible Observer/Subject Event/Response system allows for event driven design.`

## Demo

`Two demo's are available as crates:`
- lace_gel_full_demo
- lace_gel_animation_demo

## License

`ISC`

**Comment by Fabien-Chouteau** [comment]
Hi @charlie5 , I just want to let you know that you can enter the 2022 edition with the same crate if you want.
