### ISSUE TITLE
[2021][sdlada] Ada 2012 SDL 2.x bindings.

### ISSUE THREAD

**Issue by Lucretia** [AdaCore/Ada-SPARK-Crate-Of-The-Year#12]
# SDLAda
![badge](https://img.shields.io/endpoint?url=https://alire.ada.dev/badges/sdlada.json)

## Purpose

SDL 2.x provides cross-platform low-level OS primitives to handle windowing, events, basic 2D/3D drawing and other media capabilities.

SDLAda provides a type safe Ada 2012 language binding for SDL 2.x, enabling the developer to build a game or other application in less time and with less errors due to the inherent type safety of the language.

Having worked in the games industry using C and C++, I know just how badly things can go when there are no checks on the code, this library is my response to that.

## Usage

Develop portable 2D/3D games across multiple OSes and devices (toolchain allowing) with minimal changes or applications which don't require a larger GUI toolkit such as Gtk+/Qt.

## Design

This is a multi-level binding in which some functionality is thinly bound and others are bound with a thicker binding hiding the original C code underneath. There are higher level abstractions, in progress, for surfaces and textures, which will utilise a generic to wrap the C pointer of 1/2/3D image data.

## Authors

* Luke A. Guest
* Other smaller contributiors are mentioned in the README and history, bar one who sent in a patch via email, no idea who he was.

## License

Zlib

**Comment by Fabien-Chouteau** [comment]
Hi @Lucretia, I just want to let you know that you can enter the 2022 edition with the same crate if you want.
