### ISSUE TITLE
[2022][vaton] Formally verified ASCII to number conversion written in Ada/SPARK

### ISSUE THREAD

**Issue by mhatzl** [AdaCore/Ada-SPARK-Crate-Of-The-Year#16]
# [vaton](https://github.com/mhatzl/vaton)
![badge](https://img.shields.io/endpoint?url=https://alire.ada.dev/badges/vaton.json)

## Purpose

This library offers formally verified functions to convert character streams into the smallest standard type representation the resulting number may fit in.
The allowed formats are based on the [JSON-Number format](https://www.json.org/json-en.html), with the addition to allow single underscores between digits.

Vaton distinguishes itself by allowing arbitrary long number streams and converting them into the smallest supported type available.

**Note:** Arbitrary long is bound by the length of supported `Big_Integer`!

I also wanted to use the competition so get some attention on open issues, 
because I am quite stuck with the verification state of [spark_unbound](https://alire.ada.dev/crates/spark_unbound) and Vaton.

Vaton might also become part of a full unbound JSON parser written in SPARK if the current verification state improves.

## Usage

The conversion starts with the type `Number_Pieces` that is used to keep track of the different parts of a number, like fraction or exponent.
A new character is added using the `Append` procedure. After all characters have been set using `Append`, the function `To_Number` may be used
to create a number with the converted value being represented in the smallest type the value may fit in.

**Example:**

```Ada
with Vaton; use Vaton;

procedure Conversion_Test is
  Split_Number     : Vaton.Number_Pieces;
  Assembled_Number : Vaton.Number;
  Success          : Boolean;
begin
  Vaton.Append (Partial_Number => Split_Number, Character => '-', Success => Success);
  Vaton.Append (Partial_Number => Split_Number, Character => '1', Success => Success);
  Vaton.Append (Partial_Number => Split_Number, Character => '2', Success => Success);
  Vaton.Append (Partial_Number => Split_Number, Character => '3', Success => Success)

  Assembled_Number := Vaton.To_Number (Partial_Number => Split_Number);

  pragma Assert(Assembled_Number.Kind = Vaton.Integer);
  pragma Assert(Assembled_Number.Integer = -123);
end Conversion_Test;
```

## Supported Types

The `Number` type supports the following types:

- `Integer` representing `Standard.Integer`
- `Long_Integer` representing `Standard.Long_Integer`
- `Long_Long_Integer` representing `Standard.Long_Long_Integer`
- `Big_Integer` representing `Ada.Numerics.Big_Numbers.Big_Integers.Valid_Big_Integer`
- `Float` representing `Standard.Float`
- `Long_Float` representing `Standard.Long_Float`
- `Long_Long_Float` representing `Standard.Long_Long_Float`
- `Big_Real` representing `Ada.umerics.Big_Numbers.Big_Reals.Valid_Big_Real`

## Smallest Type Selection

Since the type ranges might be platform dependent, the ranges are approximated using different type attributes.

The `Size` attribute is used for discrete (integer) types, where the length of a given number must not exceed four times this size.
This approximation is based on the correlation between bit- and decimal-length being `log(10)/log(2) ~ 3.4`.
If none of the standard integers are within the length of the given number, it is converted to `Big_Integer`.

**Note:** In the GNAT implementation, Big_Integers are bound to ~1900 digits! To prevent `Contraint_Error`s, this limit is also used in Vaton.

For floating point ranges, the attributes `Machine_Emin`, `Machine_Emax` are used to get the smallest/largest exponent of a type,
and the `Digits` attribute to get the maximal precision a type supports.

**Note:** For `Big_Real` the same digit limit applies as for `Big_Integer`!

## Design

This crate was created to showcase the usage of the [spark_unbound](https://alire.ada.dev/crates/spark_unbound) crate,
by using unbound arrays to iteratively compose the converted number.

The returned `Number` type is a discriminated record that has a field per supported type, and a `Kind` that identifies the type of the returned number.

## Verification State

The conversion to `Standard.Integer` and `Standard.Long_Integer` types and big number types `Big_Integer` and `Big_Real`
is proven to be free of runtime failures, but `Standard.Long_Long_Integer` and standard floating point conversions are not proven for now. Functional correctness is also not proven for now.

To compensate missing proofs, AUnit tests where added to cover all type conversions, and some invalid states.

## License

MIT Licensed

**Comment by Fabien-Chouteau** [comment]
Nice crate @mhatzl 

> Since the type ranges might be platform dependent, the ranges are approximated using different type attributes.

Why not use the `'First` and `'Last` attributes?

**Comment by mhatzl** [comment]
Thanks 😊
I used the `Size` and `Digits` attributes to approximate the needed type based on the array lengths (number of characters added). 
With `First` and `Last` I would need to first calculate the maximum number based on the given length and then compare it against `First` or `Last`. At least that is what I thought.
