### ISSUE TITLE
[2021][Adabots] Ada-programmable robots in minecraft

### ISSUE THREAD

**Issue by TamaMcGlinn** [AdaCore/Ada-SPARK-Crate-Of-The-Year#2]
# Adabots

Everyone deserves to have Ada as their first programming language. If, like me, you are a programmer whose child(ren) have (just) learned to read, this is the best tool to teach them programming. Spare your children the resurging hype around visual drag-and-drop 'programming' and give them the best real-world programming language available with the full toolset that actual programmers use, right from the start.

Program Text               |  Demo
:-------------------------:|:-------------------------:
![](https://github.com/TamaMcGlinn/AdaBots/blob/master/demo/build_wall_program.png?raw=true)  |  ![](https://github.com/TamaMcGlinn/AdaBots/blob/master/demo/small_gif.gif?raw=true)

AdaBots is a bridge from your local machine, running e.g. GNATStudio for syntax-aware editing and the built-in debugger, to the virtual persistent environment inside Minecraft. When you run your native AdaBots program, it sends instructions over a webserver to a program running inside ComputerCraft. This also makes it possible to run this in a classroom setting, where minecraft is being shown classwide, and each student can connect their program and debugger to their own robot within Minecraft. Since these are native programs, there is no limit to what you can use - any C compatible library can easily be accessed from Ada, and the students' programs could also communicate directly with each other to synchronise on shared tasks within their virtual world.

## Usage

Create a new project directory, and issue `alr init --bin` followed by `alr with adabots`. Now you can use the high-level Adabots package to tell the robots what to do:

```ada
with Adabots;

procedure New_Project is
   Robot : constant Adabots.Turtle := Adabots.Create_Turtle;
begin
   --  Go to floor
   loop
      exit when Robot.Down = False;
   end loop;

   --  One back up
   Robot.Up;

end Build_Wall;
```

## Design

Most of the heavy work is being done elsewhere. Minecraft and the ComputerCraft mod already give us programmable robots inside a virtual voxel world, which is abstract enough to be simple and expansive enough to never get boring. Unfortunately, it does make the setup quite complex, because you will need to install that to be able to see the robots actually doing something.

Adabots uses the AWS web package to set up a local text webserver, which [a short lua program](https://github.com/TamaMcGlinn/AdaBots/blob/master/lua/httpslave) inside ComputerCraft is polling to get instructions, and to which it can post the results of functions.

## License

MIT

**Comment by Fabien-Chouteau** [comment]
Hi @TamaMcGlinn , I just want to let you know that you can enter the 2022 edition with the same crate if you want.
