### ISSUE TITLE
[2021][remoteio] Remote I/O Protocol Support

### ISSUE THREAD

**Issue by pmunts** [AdaCore/Ada-SPARK-Crate-Of-The-Year#6]
# remoteio

[![](https://img.shields.io/endpoint?url=https://alire.ada.dev/badges/remoteio.json)](https://alire.ada.dev/crates/remoteio.html)

This crate contains a subset of the **_[Linux Simple I/O Library](https://github.com/pmunts/libsimpleio)_** (aka **libsimpleio**) that is relevant to the **_[Remote I/O Protocol](http://git.munts.com/libsimpleio/doc/RemoteIOProtocol.pdf)_** (aka **remoteio**).

Nearly all of the **libsimpleio** device packages are included in this crate.

**libsimpleio**, from which this crate is excerpted, is a general purpose library I have used and continue to use for a variety of projects, including submissions to the **_Make with Ada_** contest in 2017 (**_Ada Embedded Linux Framework_**) and 2019 (**_Modbus RTU Framework for Ada_**).  I also used **remoteio**  for the educational tutorial workshop **_Controlling I/O Devices with Ada, using the Remote I/O Protocol_**  at the **_Ada-Europe 2019_** conference in Warsaw, Poland.

All source files in this crate are my original work.  Two prebuilt Windows `.dll` files, `libusb-1.0.dll` and `hidapi.dll`, are from the [libusb](https://github.com/libusb) project.

## Purpose

This crate makes it possible to create Ada software for a Linux or Windows target computer that can control I/O devices connected to a **remoteio** server device.

A first Ada program to flash an LED connected to `GPIO0` on some USB HID Remote I/O Protocol server (the embedded systems equivalent of [Hello, World!](https://en.wikipedia.org/wiki/%22Hello,_World!%22_program)) would look like:

```
WITH Ada.Text_IO; USE Ada.Text_IO;

WITH GPIO.RemoteIO;
WITH RemoteIO.Client.hidapi;

PROCEDURE test_led IS

  remdev : RemoteIO.Client.Device;
  LED    : GPIO.Pin;

BEGIN
  New_Line;
  Put_Line("USB HID Remote I/O LED test");
  New_Line;

  -- Open the remote I/O server device

  remdev := RemoteIO.Client.hidapi.Create;

  -- Configure GPIO0 to drive an LED

  LED := GPIO.RemoteIO.Create(remdev, 0, GPIO.Output);

  -- Flash the LED

  LOOP
    LED.Put(NOT LED.Get);
    DELAY 0.5;
  END LOOP;
END test_led;
```

## History

**remoteio** and its Ada client and server implementations are the result of a convergence of factors.  One was that **libsimpleio** was such a success on Linux computers that I began to wish I could use it on Windows and Mac computers as well.  Another factor was the steady removal of traditional I/O ports from personal computers.  I do a lot of physical computing, test fixture, and automation projects, and over the years my computers gradually lost the parallel ports, serial ports, and even ISA expansion slots I had been relying on to connect I/O devices.  Nowadays many laptops no longer even have wired Ethernet.  The only possibilities for I/O expansion are Bluetooth, WiFi and USB (from lowest to highest reliability, in my experience).

I spent a lot of time experimenting with and reimplementing the Labview  _**[LINX](https://www.labviewmakerhub.com/doku.php?id=libraries:linx:start)**_ protocol, which can be transported over serial lines and TCP connections.  I found some things in the **_LINX_** protocol that were incomplete or ill-conceived, but my communications with the maintainers were completely fruitless.  They weren't interested in making any improvements or finishing incomplete items, and National Instruments finally seemed to just silently abandon it.  (Fun fact: the multiple pin GPIO operations in **remoteio** were inspired by Labview **_LINX_**, but multiple device operations proved too onerous to implement for any other device type).

I also spent a period of time working with the [MCP2221](https://www.microchip.com/en-us/product/MCP2221A) USB serial port and I/O expander chip.  The MCP2221 enumerates as two USB devices: a serial port and a raw HID (Human Interface Device) I/O expander.  To a limited extent it solves the problem of connecting I/O devices to a modern PC with only USB ports for expansion.  I noticed that the MCP2221 is just a preprogrammed PIC16F1455 microcontroller by comparing the datasheets.  At about the same time I found that [Mikropascal for PIC](https://www.mikroe.com/mikropascal-pic) makes it easy to write USB device applications for even the 14-pin PIC16F1455.  As a bonus, a USB raw HID device does not require any special device driver on Windows, Linux, or Mac computers.

I am very fond of RPC (Remote Procedure Call) programming, and I eventually realized that a very minimal RPC protocol could be defined to fit in 64-byte HID reports and implemented as a raw HID device on microcontrollers as small as the PIC16F1455.  Thus was born **remoteio**.  Later I implemented support for transporting the 64-byte messages over serial lines (using the **_[Stream Framing Protocol](http://git.munts.com/libsimpleio/doc/StreamFramingProtocol.pdf)_**) for microcontrollers and/or boards lacking USB slave device support, and over networks using UDP (User Datagram Protocol), and even over [ZeroMQ](https://zeromq.org/) Request/Reply sockets.

At time of writing, the known available **remoteio** server implementations are:

- A free and open source framework written in Ada for Linux which is part of **libsimpleio**.  See [test_server_dummy.adb](https://github.com/pmunts/libsimpleio/blob/master/ada/programs/remoteio/test_server_dummy.adb).
- Some board specific example **remoteio** server Ada programs for **_[MuntsOS Embedded Linux](https://github.com/pmunts/muntsos)_** using the above framework are available [here](https://github.com/pmunts/muntsos/tree/master/examples/ada/programs).
- The **_MuntsOS Embedded Linux_** GPIO [Thin Servers](http://repo.munts.com/muntsos/thinservers) for [BeagleBone](https://beagleboard.org/black), [PocketBeagle](https://beagleboard.org/pocket), and [Raspberry Pi](https://www.raspberrypi.org/products) boards include **remoteio** support.
- Two commercial USB HID **remoteio**  server products available for purchase on [tindie.com](https://www.tindie.com/search/?q=Munts+Remote+I%2FO+Protocol), both of which use reprogrammed [Adafruit MCP2221A breakout](https://www.adafruit.com/product/4471) boards.

Some unpublished but fairly complete USB HID **remoteio** servers written in [Mikropascal for ARM](https://www.mikroe.com/mikropascal-arm) and [Mikropascal for PIC32](https://www.mikroe.com/mikropascal-pic32) also exist, as well some unfinished code using [Mbed OS](https://os.mbed.com).

A future goal is to implement a **remoteio** server for the [Raspberry Pi Pico](https://www.raspberrypi.org/products/raspberry-pi-pico), probably using either [Mbed OS ](https://os.mbed.com) or Ada.

## Design

This crate shares the layered design of the [libsimpleio](https://alire.ada.dev/crates/libsimpleio.html) crate.  The principal differences are that all packages not relevant to **remoteio**, such as those for Linux kernel devices, have been excluded, and that this crate can be used on Windows as well as Linux.

## Performance

The Remote I/O Protocol trades performance for simplicity.  As a [stop-and-wait](https://en.wikipedia.org/wiki/Flow_control_(data)#Stop-and-wait) protocol, performance is limited by the communication channel latency.

For a USB HID device, a 64-byte report may be sent or received every millisecond, as USB defines a 1 kHz polling frequency for HID devices.  Since each Remote I/O Protocol operation requires 1 command and 1 response, the maximum throughput is 500 I/O operations per second.  Extant server implementations routinely achieve this rate with both Linux and Windows clients, provided the I/O processing within the server completes in time to return the response during the next USB HID poll.

Faster network channels, such as wired Ethernet, will yield somewhat higher throughput.

## Authors

Philip Munts

## License

BSD-1-Clause

## Documentation

Crate [README.pdf](http://repo.munts.com/alire/remoteio.pdf)

[Remote I/O Protocol Specification](http://git.munts.com/libsimpleio/doc/RemoteIOProtocol.pdf)

**Comment by Fabien-Chouteau** [comment]
Hi @pmunts , I just want to let you know that you can enter the 2022 edition with the same crate if you want.
