### ISSUE TITLE
[2021][Eye Speed Tester] <An simple reaction time test>

### ISSUE THREAD

**Issue by A-Bey** [AdaCore/Ada-SPARK-Crate-Of-The-Year#9]
# <Eye Speed Tester>

## Purpose

The purpose of this crate is to test the reading speed of your eyes, you would be given an letter that would randomly change at an fast rate, and would have to press the letter it lands on accordingly, if correct, the letter it stops at should be the same as the letter typed, if incorrect, it would either carry on or tell you that the input was wrong

## Usage

Its more a fun little activity to get the brain going, brain food if you will, I’d like to implement 3 different speed levels but we’ll see how that works out, for now its main usage is a fun little reaction time tester that should involve a good chunk of letters on the keyboard

## Design

As I’ve said, once more comfortable using a slower speed, I plan on implement 2 additional difficulties (something like easy/normal/hard) with the random letter changing at different speeds for each difficulty. Once a letter is pressed by the user, if correct the random letter stops and should match the input made, where you’d then be met with a congratulatory text, if the input is wrong however, the program would either carry on or stop and give something like an ‘incorrect guess’ text and be asked if they want to try again.
If I’d want to go overboard, I could implement a feature that if a difficulty was failed 3 times, you’d get the choice to change difficulty, but only if I’m comfortable enough with the code I’ve written.

## License

SPDX

**Comment by Fabien-Chouteau** [comment]
Hello @A-Bey ,

I don't see your crate in the Alire community index yet: https://github.com/alire-project/alire-index
I will mark this submission as `not-eligible` until it is available.

Regards,
